// <auto-generated />
namespace MvcTesting.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemoveSukuLagiLagiOnAct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveSukuLagiLagiOnAct));
        
        string IMigrationMetadata.Id
        {
            get { return "201306250458387_RemoveSukuLagiLagiOnAct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
