// <auto-generated />
namespace MvcTesting.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials));
        
        string IMigrationMetadata.Id
        {
            get { return "201306250411179_initials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
