// <auto-generated />
namespace MvcTesting.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addSeveralItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSeveralItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201306260355546_addSeveralItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
